---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible jsonschema

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

before_script:
  # Create irods user
  - sudo useradd --system --home-dir /var/lib/irods irods

  # Create home directory for irods user
  - sudo mkdir --parents /var/lib/irods

  # Give irods ownership of its home directory
  - sudo chown irods:irods /var/lib/irods

script:
  # Basic role syntax check
  - ansible-playbook --syntax-check --inventory-file=tests/inventory tests/test.yml

  # Test role
  - ansible-playbook --inventory-file=tests/inventory tests/test.yml

  # Idempotence test
  - >
    ansible-playbook --inventory-file=tests/inventory tests/test.yml \
      | grep --quiet 'changed=0.*failed=0' \
      && (echo 'Idempotence test: pass' && exit 0) \
      || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
