---
- name: check if using irods_env_relative_cwd or irods_env_relative_home
  when: irods_env_relative_cwd is defined or irods_env_relative_home is defined
  fail:
    msg: <
      irods_env_relative_cwd and irods_env_relative_home have been removed. Please use irods_env_cwd
      and irods_env_home instead.

- name: validate variables
  assert:
    that:
      - _irods_env_port >= 1
      - not _irods_env_client_server_negotiation or _irods_env_client_server_negotiation in ['none', 'request_server_negotiation']
      - not _irods_env_client_server_policy or _irods_env_client_server_policy in ['CS_NEG_DONT_CARE', 'CS_NEG_REFUSE', 'CS_NEG_REQUIRE']
      - not _irods_env_control_plane_port or _irods_env_control_plane_port >= 1
      - not _irods_env_control_plane_key or _irods_env_control_plane_key | length == 32
      - not _irods_env_cwd or _irods_env_cwd | match('^/..*')
      - not _irods_env_default_hash_scheme or _irods_env_default_hash_scheme in ['MD5', 'SHA256']
      - not _irods_env_encryption_key_size or _irods_env_encryption_key_size >= 0
      - not _irods_env_encryption_num_hash_rounds or _irods_env_encryption_num_hash_rounds >= 0
      - not _irods_env_encryption_salt_size or _irods_env_encryption_salt_size >= 0
      - not _irods_env_match_hash_policy or _irods_env_match_hash_policy in ['compatible', 'strict']
      - not _irods_env_home or _irods_env_home | match('/..*')
      - not _irods_env_authentication_scheme or _irods_env_authentication_scheme in ['gsi', 'krb', 'native', 'pam']
      - not _irods_env_debug or _irods_env_debug >= 0
      - not _irods_env_log_level or _irods_env_log_level >= 0
      - not _irods_env_ssl_verify_server or _irods_env_ssl_verify_server in ['cert', 'hostname', 'none']
      - not _irods_env_xmsg_port or _irods_env_xmsg_port >= 1
  ignore_errors: true

- name: ensure path to environment file exists
  file:
    path: "{{ _irods_env_file | dirname }}"
    state: directory

- name: generate irods environment file
  template:
    src: irods_environment.json.j2
    dest: "{{ _irods_env_file }}"
    owner: "{{ _irods_env_sys_user_name }}"
    group: "{{ _irods_env_sys_group_name }}"
