---
- name: validate variables
  assert:
    that:
      - _irods_env.port >= 1
      - not _irods_env.client_server_negotiation or _irods_env.client_server_negotiation in ['none', 'request_server_negotiation']
      - not _irods_env.client_server_policy or _irods_env.client_server_policy in ['CS_NEG_DONT_CARE', 'CS_NEG_REFUSE', 'CS_NEG_REQUIRE']
      - not _irods_env.control_plane_port or _irods_env.control_plane_port >= 1
      - not _irods_env.control_plane_key or _irods_env.control_plane_key | length == 32
      - not _irods_env.cwd or _irods_env.cwd | match('^/..*')
      - not _irods_env.default_hash_scheme or _irods_env.default_hash_scheme in ['MD5', 'SHA256']
      - not _irods_env.encryption_key_size or _irods_env.encryption_key_size >= 0
      - not _irods_env.encryption_num_hash_rounds or _irods_env.encryption_num_hash_rounds >= 0
      - not _irods_env.encryption_salt_size or _irods_env.encryption_salt_size >= 0
      - not _irods_env.match_hash_policy or _irods_env.match_hash_policy in ['compatible', 'strict']
      - not _irods_env.home or _irods_env.home | match('/..*')
      - not _irods_env.authentication_scheme or _irods_env.authentication_scheme in ['gsi', 'krb', 'native', 'pam']
      - not _irods_env.debug or _irods_env.debug >= 0
      - not _irods_env.log_level or _irods_env.log_level >= 0
      - not _irods_env.ssl_verify_server or _irods_env.ssl_verify_server in ['cert', 'hostname', 'none']
      - not _irods_env.xmsg_port or _irods_env.xmsg_port >= 1
  ignore_errors: true
